//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chabelly.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class atributo_produto
    {
        public atributo_produto()
        {
            this.estoque_produto = new HashSet<estoque_produto>();
        }
    
        public long id { get; set; }
        public long tipo_atributo_id { get; set; }
        public long produto_id { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_desativacao { get; set; }
    
        public virtual ICollection<estoque_produto> estoque_produto { get; set; }
    }
}
