//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chabelly.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.categoria1 = new HashSet<categoria>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public System.DateTime data_criacao { get; set; }
        public Nullable<System.DateTime> data_desativacao { get; set; }
        public Nullable<long> usuario_destativacao { get; set; }
        public Nullable<long> categoria_pai { get; set; }
    
        public virtual ICollection<categoria> categoria1 { get; set; }
        public virtual categoria categoria2 { get; set; }
    }
}
