//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chabelly.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class foto_produto
    {
        public long id { get; set; }
        public string nome_foto { get; set; }
        public long produto_id { get; set; }
        public Nullable<int> ordem { get; set; }
    
        public virtual produto produto { get; set; }
    }
}
