//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chabelly.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissoes
    {
        public permissoes()
        {
            this.grupo = new HashSet<grupo>();
        }
    
        public long id { get; set; }
        public string sigla { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<grupo> grupo { get; set; }
    }
}
