//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chabelly.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.estoque_produto = new HashSet<estoque_produto>();
            this.foto_produto = new HashSet<foto_produto>();
            this.historico_estoque = new HashSet<historico_estoque>();
            this.preco_produto = new HashSet<preco_produto>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string codigo_referencia { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public Nullable<long> foto_id { get; set; }
        public Nullable<long> categoria_id { get; set; }
        public Nullable<System.DateTime> data_desativacao { get; set; }
    
        public virtual ICollection<estoque_produto> estoque_produto { get; set; }
        public virtual ICollection<foto_produto> foto_produto { get; set; }
        public virtual ICollection<historico_estoque> historico_estoque { get; set; }
        public virtual ICollection<preco_produto> preco_produto { get; set; }
    }
}
