//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chabelly.Model
{
    using System;
    using System.Collections.Generic;
   
    public partial class usuario
    {
        public usuario()
        {
            this.contato_usuario = new HashSet<contato_usuario>();
            this.enderecos = new HashSet<enderecos>();
            this.grupo = new HashSet<grupo>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public long dominio_id { get; set; }
        public System.DateTime data_criacao { get; set; }
        public Nullable<System.DateTime> data_desativacao { get; set; }
        public Nullable<long> endereco_principal { get; set; }
    
        public virtual ICollection<contato_usuario> contato_usuario { get; set; }
        public virtual dominio dominio { get; set; }
        public virtual ICollection<enderecos> enderecos { get; set; }
        public virtual ICollection<grupo> grupo { get; set; }
    }
}
